export type ElementSeries = "lanthanide" | "actinide";

export type ChemicalElement = {
  atomicNumber: number;
  symbol: string;
  name: string;
  period: number;
  group?: number;
  series?: ElementSeries;
};

export const ELEMENTS: ChemicalElement[] = [
  { atomicNumber: 1, symbol: "H", name: "Hydrogen", period: 1, group: 1 },
  { atomicNumber: 2, symbol: "He", name: "Helium", period: 1, group: 18 },
  { atomicNumber: 3, symbol: "Li", name: "Lithium", period: 2, group: 1 },
  { atomicNumber: 4, symbol: "Be", name: "Beryllium", period: 2, group: 2 },
  { atomicNumber: 5, symbol: "B", name: "Boron", period: 2, group: 13 },
  { atomicNumber: 6, symbol: "C", name: "Carbon", period: 2, group: 14 },
  { atomicNumber: 7, symbol: "N", name: "Nitrogen", period: 2, group: 15 },
  { atomicNumber: 8, symbol: "O", name: "Oxygen", period: 2, group: 16 },
  { atomicNumber: 9, symbol: "F", name: "Fluorine", period: 2, group: 17 },
  { atomicNumber: 10, symbol: "Ne", name: "Neon", period: 2, group: 18 },
  { atomicNumber: 11, symbol: "Na", name: "Sodium", period: 3, group: 1 },
  { atomicNumber: 12, symbol: "Mg", name: "Magnesium", period: 3, group: 2 },
  { atomicNumber: 13, symbol: "Al", name: "Aluminum", period: 3, group: 13 },
  { atomicNumber: 14, symbol: "Si", name: "Silicon", period: 3, group: 14 },
  { atomicNumber: 15, symbol: "P", name: "Phosphorus", period: 3, group: 15 },
  { atomicNumber: 16, symbol: "S", name: "Sulfur", period: 3, group: 16 },
  { atomicNumber: 17, symbol: "Cl", name: "Chlorine", period: 3, group: 17 },
  { atomicNumber: 18, symbol: "Ar", name: "Argon", period: 3, group: 18 },
  { atomicNumber: 19, symbol: "K", name: "Potassium", period: 4, group: 1 },
  { atomicNumber: 20, symbol: "Ca", name: "Calcium", period: 4, group: 2 },
  { atomicNumber: 21, symbol: "Sc", name: "Scandium", period: 4, group: 3 },
  { atomicNumber: 22, symbol: "Ti", name: "Titanium", period: 4, group: 4 },
  { atomicNumber: 23, symbol: "V", name: "Vanadium", period: 4, group: 5 },
  { atomicNumber: 24, symbol: "Cr", name: "Chromium", period: 4, group: 6 },
  { atomicNumber: 25, symbol: "Mn", name: "Manganese", period: 4, group: 7 },
  { atomicNumber: 26, symbol: "Fe", name: "Iron", period: 4, group: 8 },
  { atomicNumber: 27, symbol: "Co", name: "Cobalt", period: 4, group: 9 },
  { atomicNumber: 28, symbol: "Ni", name: "Nickel", period: 4, group: 10 },
  { atomicNumber: 29, symbol: "Cu", name: "Copper", period: 4, group: 11 },
  { atomicNumber: 30, symbol: "Zn", name: "Zinc", period: 4, group: 12 },
  { atomicNumber: 31, symbol: "Ga", name: "Gallium", period: 4, group: 13 },
  { atomicNumber: 32, symbol: "Ge", name: "Germanium", period: 4, group: 14 },
  { atomicNumber: 33, symbol: "As", name: "Arsenic", period: 4, group: 15 },
  { atomicNumber: 34, symbol: "Se", name: "Selenium", period: 4, group: 16 },
  { atomicNumber: 35, symbol: "Br", name: "Bromine", period: 4, group: 17 },
  { atomicNumber: 36, symbol: "Kr", name: "Krypton", period: 4, group: 18 },
  { atomicNumber: 37, symbol: "Rb", name: "Rubidium", period: 5, group: 1 },
  { atomicNumber: 38, symbol: "Sr", name: "Strontium", period: 5, group: 2 },
  { atomicNumber: 39, symbol: "Y", name: "Yttrium", period: 5, group: 3 },
  { atomicNumber: 40, symbol: "Zr", name: "Zirconium", period: 5, group: 4 },
  { atomicNumber: 41, symbol: "Nb", name: "Niobium", period: 5, group: 5 },
  { atomicNumber: 42, symbol: "Mo", name: "Molybdenum", period: 5, group: 6 },
  { atomicNumber: 43, symbol: "Tc", name: "Technetium", period: 5, group: 7 },
  { atomicNumber: 44, symbol: "Ru", name: "Ruthenium", period: 5, group: 8 },
  { atomicNumber: 45, symbol: "Rh", name: "Rhodium", period: 5, group: 9 },
  { atomicNumber: 46, symbol: "Pd", name: "Palladium", period: 5, group: 10 },
  { atomicNumber: 47, symbol: "Ag", name: "Silver", period: 5, group: 11 },
  { atomicNumber: 48, symbol: "Cd", name: "Cadmium", period: 5, group: 12 },
  { atomicNumber: 49, symbol: "In", name: "Indium", period: 5, group: 13 },
  { atomicNumber: 50, symbol: "Sn", name: "Tin", period: 5, group: 14 },
  { atomicNumber: 51, symbol: "Sb", name: "Antimony", period: 5, group: 15 },
  { atomicNumber: 52, symbol: "Te", name: "Tellurium", period: 5, group: 16 },
  { atomicNumber: 53, symbol: "I", name: "Iodine", period: 5, group: 17 },
  { atomicNumber: 54, symbol: "Xe", name: "Xenon", period: 5, group: 18 },
  { atomicNumber: 55, symbol: "Cs", name: "Cesium", period: 6, group: 1 },
  { atomicNumber: 56, symbol: "Ba", name: "Barium", period: 6, group: 2 },
  { atomicNumber: 57, symbol: "La", name: "Lanthanum", period: 6, series: "lanthanide" },
  { atomicNumber: 58, symbol: "Ce", name: "Cerium", period: 6, series: "lanthanide" },
  { atomicNumber: 59, symbol: "Pr", name: "Praseodymium", period: 6, series: "lanthanide" },
  { atomicNumber: 60, symbol: "Nd", name: "Neodymium", period: 6, series: "lanthanide" },
  { atomicNumber: 61, symbol: "Pm", name: "Promethium", period: 6, series: "lanthanide" },
  { atomicNumber: 62, symbol: "Sm", name: "Samarium", period: 6, series: "lanthanide" },
  { atomicNumber: 63, symbol: "Eu", name: "Europium", period: 6, series: "lanthanide" },
  { atomicNumber: 64, symbol: "Gd", name: "Gadolinium", period: 6, series: "lanthanide" },
  { atomicNumber: 65, symbol: "Tb", name: "Terbium", period: 6, series: "lanthanide" },
  { atomicNumber: 66, symbol: "Dy", name: "Dysprosium", period: 6, series: "lanthanide" },
  { atomicNumber: 67, symbol: "Ho", name: "Holmium", period: 6, series: "lanthanide" },
  { atomicNumber: 68, symbol: "Er", name: "Erbium", period: 6, series: "lanthanide" },
  { atomicNumber: 69, symbol: "Tm", name: "Thulium", period: 6, series: "lanthanide" },
  { atomicNumber: 70, symbol: "Yb", name: "Ytterbium", period: 6, series: "lanthanide" },
  { atomicNumber: 71, symbol: "Lu", name: "Lutetium", period: 6, series: "lanthanide" },
  { atomicNumber: 72, symbol: "Hf", name: "Hafnium", period: 6, group: 4 },
  { atomicNumber: 73, symbol: "Ta", name: "Tantalum", period: 6, group: 5 },
  { atomicNumber: 74, symbol: "W", name: "Tungsten", period: 6, group: 6 },
  { atomicNumber: 75, symbol: "Re", name: "Rhenium", period: 6, group: 7 },
  { atomicNumber: 76, symbol: "Os", name: "Osmium", period: 6, group: 8 },
  { atomicNumber: 77, symbol: "Ir", name: "Iridium", period: 6, group: 9 },
  { atomicNumber: 78, symbol: "Pt", name: "Platinum", period: 6, group: 10 },
  { atomicNumber: 79, symbol: "Au", name: "Gold", period: 6, group: 11 },
  { atomicNumber: 80, symbol: "Hg", name: "Mercury", period: 6, group: 12 },
  { atomicNumber: 81, symbol: "Tl", name: "Thallium", period: 6, group: 13 },
  { atomicNumber: 82, symbol: "Pb", name: "Lead", period: 6, group: 14 },
  { atomicNumber: 83, symbol: "Bi", name: "Bismuth", period: 6, group: 15 },
  { atomicNumber: 84, symbol: "Po", name: "Polonium", period: 6, group: 16 },
  { atomicNumber: 85, symbol: "At", name: "Astatine", period: 6, group: 17 },
  { atomicNumber: 86, symbol: "Rn", name: "Radon", period: 6, group: 18 },
  { atomicNumber: 87, symbol: "Fr", name: "Francium", period: 7, group: 1 },
  { atomicNumber: 88, symbol: "Ra", name: "Radium", period: 7, group: 2 },
  { atomicNumber: 89, symbol: "Ac", name: "Actinium", period: 7, series: "actinide" },
  { atomicNumber: 90, symbol: "Th", name: "Thorium", period: 7, series: "actinide" },
  { atomicNumber: 91, symbol: "Pa", name: "Protactinium", period: 7, series: "actinide" },
  { atomicNumber: 92, symbol: "U", name: "Uranium", period: 7, series: "actinide" },
  { atomicNumber: 93, symbol: "Np", name: "Neptunium", period: 7, series: "actinide" },
  { atomicNumber: 94, symbol: "Pu", name: "Plutonium", period: 7, series: "actinide" },
  { atomicNumber: 95, symbol: "Am", name: "Americium", period: 7, series: "actinide" },
  { atomicNumber: 96, symbol: "Cm", name: "Curium", period: 7, series: "actinide" },
  { atomicNumber: 97, symbol: "Bk", name: "Berkelium", period: 7, series: "actinide" },
  { atomicNumber: 98, symbol: "Cf", name: "Californium", period: 7, series: "actinide" },
  { atomicNumber: 99, symbol: "Es", name: "Einsteinium", period: 7, series: "actinide" },
  { atomicNumber: 100, symbol: "Fm", name: "Fermium", period: 7, series: "actinide" },
  { atomicNumber: 101, symbol: "Md", name: "Mendelevium", period: 7, series: "actinide" },
  { atomicNumber: 102, symbol: "No", name: "Nobelium", period: 7, series: "actinide" },
  { atomicNumber: 103, symbol: "Lr", name: "Lawrencium", period: 7, series: "actinide" },
  { atomicNumber: 104, symbol: "Rf", name: "Rutherfordium", period: 7, group: 4 },
  { atomicNumber: 105, symbol: "Db", name: "Dubnium", period: 7, group: 5 },
  { atomicNumber: 106, symbol: "Sg", name: "Seaborgium", period: 7, group: 6 },
  { atomicNumber: 107, symbol: "Bh", name: "Bohrium", period: 7, group: 7 },
  { atomicNumber: 108, symbol: "Hs", name: "Hassium", period: 7, group: 8 },
  { atomicNumber: 109, symbol: "Mt", name: "Meitnerium", period: 7, group: 9 },
  { atomicNumber: 110, symbol: "Ds", name: "Darmstadtium", period: 7, group: 10 },
  { atomicNumber: 111, symbol: "Rg", name: "Roentgenium", period: 7, group: 11 },
  { atomicNumber: 112, symbol: "Cn", name: "Copernicium", period: 7, group: 12 },
  { atomicNumber: 113, symbol: "Nh", name: "Nihonium", period: 7, group: 13 },
  { atomicNumber: 114, symbol: "Fl", name: "Flerovium", period: 7, group: 14 },
  { atomicNumber: 115, symbol: "Mc", name: "Moscovium", period: 7, group: 15 },
  { atomicNumber: 116, symbol: "Lv", name: "Livermorium", period: 7, group: 16 },
  { atomicNumber: 117, symbol: "Ts", name: "Tennessine", period: 7, group: 17 },
  { atomicNumber: 118, symbol: "Og", name: "Oganesson", period: 7, group: 18 },
];

export const PERIODIC_TABLE_ELEMENT_COUNT = ELEMENTS.length;